name: CI

on: push

jobs:
  build-and-test:
    runs-on: macos-15

    steps:
    - uses: actions/checkout@v4

    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_16.2.app

    - name: Build and test
      run: |
        xcodebuild clean build test \
          -project EssentialFeed/EssentialFeed.xcodeproj \
          -scheme "CI_macOS" \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          SWIFT_TREAT_WARNINGS_AS_ERRORS=YES \
          OTHER_SWIFT_FLAGS="-D ED_SKIP_SWIFT_FORMAT"
        xcodebuild clean build test \
          -workspace EssentialFeed-Starter-Project/EssentialApp.xcworkspace \
          -scheme "CI_iOS" \
          -sdk iphonesimulator \
          -destination "platform=iOS Simulator,name=iPhone 16 Pro,OS=18.2" \
          ONLY_ACTIVE_ARCH=YES \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          SWIFT_TREAT_WARNINGS_AS_ERRORS=YES \
          OTHER_SWIFT_FLAGS="-D ED_SKIP_SWIFT_FORMAT"
